function out1 = d_pcor_d_f(q,ta,tb)
%D_PCOR_D_F
%    OUT1 = D_PCOR_D_F(Q,TA,TB)

%    This function was generated by the Symbolic Math Toolbox version 26.1.
%    07-Sep-2026 13:40:40

t2 = ta.^2;
t3 = tb.^2;
out1 = -(q.*(t2+t3))./(t2+t3+1.0);
end