function [y,BX,ZF,nfilt] = decimateByFactors(varargin)
%DECIMATE Resample data at a lower rate after lowpass filtering.
%   Y = DECIMATE(X,R) resamples the sequence in vector X at 1/R times the
%   original sample rate.  The resulting resampled vector Y is R times
%   shorter, i.e., LENGTH(Y) = CEIL(LENGTH(X)/R). By default, DECIMATE
%   filters the data with an 8th order Chebyshev Type I lowpass filter with
%   cutoff frequency .8*(Fs/2)/R, before resampling.
%
%   Y = DECIMATE(X,R,N) uses an N'th order Chebyshev filter.  For N greater
%   than 13, DECIMATE will produce a warning regarding the unreliability of
%   the results.  See NOTE below.
%
%   Y = DECIMATE(X,R,'FIR') uses a 30th order FIR filter generated by
%   FIR1(30,1/R) to filter the data.
%
%   Y = DECIMATE(X,R,N,'FIR') uses an Nth FIR filter.
%
%   Note: For better results when R is large (i.e., R > 13), it is
%   recommended to break R up into its factors and calling DECIMATE several
%   times.
%
%   EXAMPLE: Decimate a signal by a factor of four
%   t = 0:.00025:1;  % Time vector
%   x = sin(2*pi*30*t) + sin(2*pi*60*t);
%   y = decimate(x,4);
%   subplot(1,2,1);
%   stem(x(1:120)), axis([0 120 -2 2])   % Original signal
%   title('Original Signal')
%   subplot(1,2,2);
%   stem(y(1:30))                        % Decimated signal
%   title('Decimated Signal')
%
%   See also DOWNSAMPLE, INTERP, RESAMPLE, FILTFILT, FIR1, CHEBY1.

%   Author(s): L. Shure, 6-4-87
%              L. Shure, 12-11-88, revised
%   Copyright 1988-2022 The MathWorks, Inc.

%   References:
%    [1] "Programs for Digital Signal Processing", IEEE Press
%         John Wiley & Sons, 1979, Chap. 8.3.
%#codegen
idata=varargin{1};
r=varargin{2};
if(r==1)
    y=idata;
    BX=[];
    ZF=[];
    ndfilt=[];
    return
end    

BI=0;ZI=0;ZF=0;

isMATLAB = coder.target('MATLAB');
if ~isMATLAB
coder.internal.errorIf(useCheby,'signal:decimate:codegenNeedsFir');
end

nd = length(idata);
nout = ceil(nd/r);
isRow = coder.internal.isConstTrue(isrow(idata));
if true	% FIR filter by default
nfilt=400;
Wpass=0.9/r;
Wstop=1.2/r;
f = [0 Wpass Wstop 1];      % Frequency breakpoints
m = [1 1 0 0]; 
b = fir2(nfilt,f,m);
BX = b;
ZF=0;


% prepend sequence with mirror image of first points so that transients
% can be eliminated. then do same thing at right end of data sequence.
nfilt = nfilt+1;
initItemp = 2*idata(1) - idata((nfilt+1):-1:2);
[~,zi]=filter(b,1,initItemp);
[odata,zf] = filter(b,1,idata,zi);
ZF=zf;
if isRow	% row data
itemp = coder.nullcopy(zeros(1,2*nfilt,'like',idata));
else	% column data
itemp = coder.nullcopy(zeros(2*nfilt,1,'like',idata));
end
itemp(:) = 2*idata(nd)-idata((nd-1):-1:(nd-2*nfilt));
itemp = filter(b,1,itemp,zf);
itemp=circshift(itemp,-fix(nfilt/2)); % shift nfilt/2 points
% finally, select only every r'th point from the interior of the lowpass
% filtered sequence
gd = grpdelay(b,1,8);
if isMATLAB
list =round(gd(1)+1.25):r:nd;
odata = odata(list);
lod = length(odata);
nlen = nout - lod;
nbeg = r - (nd - list(length(list)));
if isRow	% row data
y = [odata itemp(nbeg:r:nbeg+nlen*r-1)];
else
y = [odata; itemp(nbeg:r:nbeg+nlen*r-1)];
end
else
nd = coder.internal.indexInt(nd);
nout = coder.internal.indexInt(nout);
r = coder.internal.indexInt(r);
beg = coder.internal.indexInt(round(gd(1)+1.25));
lod = coder.internal.indexDivide(nd-beg,r) + coder.internal.indexInt(1);
nend = beg + (lod-1)*r;
assert(nout <= nd); %<HINT>
if isRow
y = coder.nullcopy(zeros(1,nout,'like',idata));
else
y = coder.nullcopy(zeros(nout,1,'like',idata));
end
for i = 1:lod
y(i) = odata(beg+(i-1)*r);
end
nbeg = r - (nd - nend);
k = nbeg;
for i = lod+1:nout
y(i) = itemp(k);
k = k + r;
end
end
end
if(~exist('b')),b=[],end

return
