function out1 = fqCalc(dpa,dpb,dpr)
%
%    OUT1 = FQ_CALC(DPA,DPB,DPR)

%    This function was generated by the Symbolic Math Toolbox version 25.2.
%    06-Feb-2026 06:47:01

t2 = dpr.*2.0;
t3 = dpb.^2;
out1 = dpb+t2-((t3.*2.0+dpa.^2).*(dpb+t2-sqrt(2.0).*sqrt(t3+dpb.*t2+dpr.*t2)))./(t3.*2.0);
end
