function q = impactPcalc(dp1a,dpa,dpb,dpr)
% Calculate dynamic pressure from 868
%    q = impactPcalc(DP1A,DPA,DPB,DPR)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    28-Apr-2025 10:46:31

t2 = dpb.^2;
q = dp1a-((t2+dpa.^2).*(dpb+dpr.*2.0-sqrt(2.0).*sqrt(t2+dpb.*dpr.*2.0+dpr.^2.*2.0)))./(t2.*2.0);
end


