function out1 = pcor_beta(dp1a,dpa,dpb,dpr,f,fq)
%PCOR_BETA
%    OUT1 = PCOR_BETA(DP1A,DPA,DPB,DPR,F,FQ)

%    This function was generated by the Symbolic Math Toolbox version 25.2.
%    20-May-2026 09:34:00

t2 = dpr.*2.0;
t3 = dpa.^2;
t5 = dpb.^2;
t6 = dpb.^3;
t8 = dpb.^5;
t9 = dpr.^2;
t10 = dpr.^3;
t12 = 1.0./dpb;
t14 = sqrt(2.0);
t4 = t3.^2;
t7 = t5.^2;
t11 = dpb.*t2;
t13 = dpr.*t2;
t15 = t5+t11+t13;
t16 = sqrt(t15);
t17 = t14.*t16;
t18 = -t17;
t19 = dpb+t2+t18;
et1 = dpr.*t8.*-6.4e+1-t4.*t5.*2.0-t3.*t7.*1.6e+1-t6.*t10.*6.4e+1-t7.*t9.*9.6e+1+t8.*t19.*1.6e+1-t5.^3.*1.6e+1+t3.^3.*t12.*t19-dpb.*dpr.*t4.*4.0+dp1a.*f.*t8.*1.6e+1+f.*fq.*t8.*4.0-dpb.*t3.*t10.*6.4e+1+dpb.*t4.*t19.*1.0e+1-dpr.*t3.*t6.*6.4e+1+dpr.*t4.*t19.*1.6e+1+dpr.*t7.*t19.*3.2e+1-t3.*t5.*t9.*9.6e+1+t3.*t6.*t19.*2.4e+1+t6.*t9.*t19.*3.2e+1+dp1a.*dpb.*f.*t4.*2.0+dp1a.*dpr.*f.*t7.*3.2e+1+dpb.*f.*fq.*t4.*2.0+dp1a.*f.*t3.*t6.*1.6e+1+dp1a.*f.*t6.*t9.*3.2e+1+f.*fq.*t3.*t6.*6.0+f.*fq.*t7.*t19.*4.0+dpb.*t3.*t9.*t19.*4.8e+1+dpr.*t3.*t5.*t19.*4.8e+1+t4.*t9.*t12.*t19.*1.6e+1+dp1a.*dpb.*f.*t3.*t9.*3.2e+1;
et2 = dp1a.*dpr.*f.*t3.*t5.*3.2e+1+dpr.*f.*fq.*t6.*t19.*8.0+f.*fq.*t3.*t5.*t19.*4.0+dpb.*dpr.*f.*fq.*t3.*t19.*8.0;
out1 = -(et1+et2)./(f.*t8.*1.6e+1+dpb.*f.*t4.*2.0+dpr.*f.*t7.*3.2e+1+f.*t3.*t6.*1.6e+1+f.*t6.*t9.*3.2e+1+dpb.*f.*t3.*t9.*3.2e+1+dpr.*f.*t3.*t5.*3.2e+1);
end
