function out1 = pcor_alpha(dp1a,dpa,dpb,dpra,f,fq)
%PCOR_ALPHA
%    OUT1 = PCOR_ALPHA(DP1A,DPA,DPB,DPRA,F,FQ)

%    This function was generated by the Symbolic Math Toolbox version 25.2.
%    20-May-2026 09:34:00

t2 = dpa.*dpb;
t3 = dpa.^2;
t4 = dpa.^3;
t6 = dpb.^2;
t7 = dpb.^3;
t9 = dpb.^5;
t10 = dpra.^2;
t11 = dpra.^3;
t12 = dpa.*dpra.*2.0;
t13 = dpb.*dpra.*2.0;
t16 = sqrt(2.0);
t5 = t3.^2;
t8 = t6.^2;
t14 = 1.0./t3;
t15 = t10.*2.0;
t17 = t3+t12+t15;
t18 = sqrt(t17);
t19 = dpb.*t16.*t18;
t20 = -t19;
t21 = t2+t13+t20;
et1 = dpra.*t9.*-4.0-t2.*t5.*1.6e+1-t2.*t8.*2.0-t7.*t11.*6.4e+1+t5.*t21.*1.6e+1+t8.*t21.*1.0e+1+t2.^2.*t21.*2.4e+1-t2.^3.*1.6e+1+t6.^3.*t14.*t21+dp1a.*f.*t9.*2.0+f.*fq.*t9.*2.0-dpa.*t2.*t11.*6.4e+1-dpra.*t2.*t4.*6.4e+1+dpra.*t4.*t21.*3.2e+1-t2.*t3.*t10.*9.6e+1-t2.*t6.*t10.*9.6e+1+t3.*t10.*t21.*3.2e+1+t6.*t10.*t21.*4.8e+1-dpb.*dpra.*t2.^2.*6.4e+1+dpb.*dpra.*t2.*t21.*4.8e+1+dp1a.*f.*t2.*t4.*1.6e+1+dp1a.*f.*t7.*t10.*3.2e+1+f.*fq.*t2.*t4.*4.0+f.*fq.*t4.*t21.*4.0+t8.*t10.*t14.*t21.*1.6e+1+dp1a.*dpb.*f.*t2.^2.*1.6e+1+dpb.*f.*fq.*t2.^2.*6.0+(dpra.*t8.*t21.*1.6e+1)./dpa+dp1a.*dpa.*f.*t2.*t10.*3.2e+1;
et2 = dp1a.*dpra.*f.*t2.*t3.*3.2e+1+dp1a.*dpra.*f.*t2.*t6.*3.2e+1+dpb.*f.*fq.*t2.*t21.*4.0+dpra.*f.*fq.*t3.*t21.*8.0+dpra.*f.*fq.*t6.*t21.*8.0;
out1 = -(et1+et2)./(f.*t9.*2.0+f.*t2.*t4.*1.6e+1+f.*t7.*t10.*3.2e+1+dpb.*f.*t2.^2.*1.6e+1+dpa.*f.*t2.*t10.*3.2e+1+dpra.*f.*t2.*t3.*3.2e+1+dpra.*f.*t2.*t6.*3.2e+1);
end
