function out1 = q_beta(dp1a,dpa,dpb,dpr)
%Q_BETA
%    OUT1 = Q_BETA(DP1A,DPA,DPB,DPR)

%    This function was generated by the Symbolic Math Toolbox version 25.2.
%    20-May-2026 09:33:59

t2 = dpb.^2;
out1 = dp1a-((t2+dpa.^2).*(dpb+dpr.*2.0-sqrt(2.0).*sqrt(t2+dpb.*dpr.*2.0+dpr.^2.*2.0)))./(t2.*2.0);
end
