function ta = tanAlpha(dpa,dpb,dpr)
% calculate tangent of attack angle alpha
%    ta = tanAlpha(DPA,DPB,DPR)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    28-Apr-2025 10:46:30

t2 = dpr.*2.0;
ta = -dpa.*1.0./dpb.^2.*(dpb+t2-sqrt(2.0).*sqrt(dpb.*t2+dpr.*t2+dpb.^2));
end
