function tb = tanBeta(dpb,dpr)
% calculate tan of sideslip angle beta
%    tb = tanBeta(DPB,DPR)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    28-Apr-2025 10:46:30

t2 = dpr.*2.0;
tb = -(dpb+t2-sqrt(2.0).*sqrt(dpb.*t2+dpr.*t2+dpb.^2))./dpb;
end
